name: Mirror IntelliJ Plugins

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - run: pip install requests beautifulsoup4

      - name: Mirror plugins
        run: python jbmirror.py

      - name: Generate updatePlugins.xml
        run: python generate_xml.py

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
